name: Deployment To Staging
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: actions checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.18"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "${{ secrets.DEV_AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}"
          aws-region: "${{ secrets.DEV_AWS_REGION }}"

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Setup Env dependencies
        run: |
          echo "${{vars.DEV_ENV}}" > .env

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: |
          export REACT_APP_BASE_URL="https://dev-api.creatorwrk.com/user/v1"
          export REACT_APP_CHAT_URL="https://dev-chat.creatorwrk.com/v1/chat"
          export REACT_APP_LANDING_PAGE_URL="https://dev.creatorwrk.com"
          export REACT_APP_RECAPTCHA_KEY="6LcixOYpAAAAAOOQ0N-IPY0DJXyWY7bHaT4vsk1C"
          npm run build

      - name: Deploy to AWS S3
        run: |
          aws s3 sync build s3://${{ secrets.DEV_S3_BUCKET_NAME }} --delete
      - name: Invalidate CloudFront cache
        run: >
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
